spring:
  profiles:
    active: common # 현재 사용할 프로필 설정
    group: # 특정 프로필을 실행할때, 같이 실행할 프로필
      common: secret # common이 실행될때, secret 프로필도 같이 실행해아

---
spring:
  config:
    activate:
      on-profile: common # 이 블록은 common 프로필 활성화시 로드됩니다.

# MyBatis 설정
mybatis:
  # Xml파일로 sql쿼리를 관리할텐데, 자바와 연결할 수 있는 파일들의 위치정의
  mapper-locations: classpath:mapper/*.xml
  # entity타입을 인식
  type-aliases-package: com.study.koreait.entity
  configuration:
    # 자동으로 카멜케이스로 변환해주는 옵션
    map-underscore-to-camel-case: true
